import re
import requests

list_sites = ["http://www.bigyellow.co.uk", "https://www.bigyellow.co.uk", "https://www.accessstorage.com", "http://www.redcubestorage.co.uk",
              "https://www.safestore.co.uk", "http://www.fortselfstorage.co.uk", "https://www.alligatorstorage.co.uk",
              "http://squirrelstorage.co.uk", "https://admiralstorage.co.uk", "https://www.readysteadystore.com",
              "http://www.mjmccarthy.co.uk", "http://www.thestoreroom.co.uk", "https://www.storefirst.com",
              "http://www.admiralsyard.co.uk", "http://akstoragesolutions.co.uk", "http://www.boylinsselfstore.co.uk",
              "http://www.abcastle.co.uk", "http://www.junction30storage.co.uk", "http://www.dainton.com",
              "http://www.low-cost-self-storage-newquay.co.uk", "http://www.dashselfstore.co.uk",
              "http://www.ukstoragecompany.co.uk", "http://www.newquay-selfstorage.co.uk", "http://www.allstore.co.uk",
              "https://www.tripp-removals.co.uk", "http://www.britannialanes.co.uk", "http://www.m-store.biz",
              "http://stadiumstorage.co.uk", "http://incrediblebulkstorage.co.uk", "http://www.darvills.co.uk",
              "http://www.selfstoragetameside.co.uk", "http://www.cheapstoragemanchester.co.uk",
              "http://flexispace.com", "http://www.apexselfstorage.co.uk", "http://www.manchesterselfstorage.co.uk",
              "https://www.durhamselfstore.com", "https://www.uholdthekey.co.uk", "http://www.nelsonsofdurham.co.uk",
              "http://www.jaysstorage24.com", "https://www.storenextdoor.com", "http://www.studentstoragebox.co.uk",
              "http://www.southweststoragesolutions.co.uk", "http://www.southwickstorage.co.uk",
              "http://www.blackholestorage.co.uk", "http://chippenhamselfstorage.com", "http://www.pickfords.co.uk",
              "http://www.swindon-storage.com", "http://www.rhinostoragesalisbury.co.uk",
              "https://www.storageking.co.uk", "https://www.containercare.uk", "http://www.bigpadlock.co.uk",
              "http://usss-liverpool.com", "https://www.smart-storage.co.uk", "http://www.selfstorage-liverpool.co.uk",
              "https://www.rentaspace.today", "http://www.redspotstorage.co.uk",
              "http://www.spacecentreselfstorage.co.uk", "http://www.loknstore.co.uk", "https://www.kellystorage.co.uk",
              "http://www.excelselfstorage.co.uk", "http://www.cakvs.co.uk", "http://www.dsdremovalsltd.com",
              "http://www.curriestorage.co.uk", "http://www.a1selfstorage.co.uk", "http://containersafe.co.uk",
              "http://www.simplystorelondon.com", "http://www.morrisremovals.co.uk",
              "http://www.supremeselfstorage.co.uk", "http://www.shurgard.co.uk", "http://www.sandersteads.com",
              "https://lowcoststorage.co.uk", "http://www.fsmithandson.co.uk", "http://www.coventryselfstorage.co.uk",
              "https://www.storagebase.com", "http://simplestoragesolutions.co.uk",
              "http://www.extraroomselfstorage.co.uk", "http://www.hillviewselfstorage.com",
              "http://www.magentastorage.co.uk", "http://storageealing.co.uk", "http://www.fortbox.co.uk",
              "https://lovespace.co.uk", "http://www.space-station.co.uk", "http://www.simpleselfstorage.co.uk",
              "https://www.spaceplace.co.uk", "http://ezeeystorage.co.uk", "http://stjohnsselfstorageleicester.co.uk",
              "https://beyondstorage.co.uk", "http://www.billesdonselfstorage.co.uk", "http://www.beverley24.co.uk",
              "http://www.hilltopcaravanstorage.co.uk", "http://www.bishopsmove.com",
              "http://www.cranswickcaravanstorage.co.uk", "http://www.cheshirewestandchesterremovals.co.uk",
              "http://www.mobilemini.co.uk", "https://www.atticstorage.co.uk", "http://www.storagecollect.co.uk",
              "http://www.bigandred.co.uk", "http://www.ustore-it.co.uk", "http://www.spaceplaceselfstorage.com",
              "http://storagebromley.co.uk", "http://www.abcselfstore.co.uk", "http://www.lambeth.org.uk",
              "https://storebox.co.uk", "http://www.storage-units.co.uk", "http://www.edwardsstorage.co.uk",
              "http://www.storageinwigan.co.uk", "http://www.wiganselfstore.com",
              "http://www.selfstoragestandish.co.uk", "http://www.strongboxselfstorage.co.uk",
              "http://www.championstorage-wirral.co.uk", "http://www.adamsselfstore.co.uk",
              "http://www.caravanstoragewirral.com", "http://lock-and-store.co.uk",
              "http://www.securestorageservices.co.uk", "http://www.charterhouse-removals.co.uk",
              "http://www.jumbostoragenottingham.co.uk", "http://www.storage4unottingham.co.uk",
              "http://www.storageexperts.co.uk", "http://www.hillcreststorage.co.uk",
              "http://www.anchorselfstoragedudley.co.uk", "http://www.rentcontainer.com",
              "http://www.ucanstoreit.co.uk", "http://www.fergyspace.com", "http://www.swarlandfence.co.uk",
              "http://storagexpress.co.uk", "http://www.smalessecurestorage.co.uk", "http://www.easymovene.co.uk",
              "http://www.storeitsafenortheast.com", "http://alancarrollremovals.co.uk", "http://lockandleave.co.uk",
              "http://www.wandsworth.gov.uk", "http://www.shropshireselfstorage.co.uk",
              "http://www.longpoolscaravanstorage.co.uk", "http://www.storagemaster.co.uk",
              "http://www.cravenselfstorage.com", "http://www.myextrastorage.co.uk",
              "http://www.muckleyfarmstorage.co.uk", "http://cubestoragesolutions.co.uk",
              "http://www.blue-box-storage.co.uk", "http://www.ustoredoncaster.co.uk", "http://www.jscbrough.co.uk",
              "http://www.wrightstorage.co.uk", "http://www.paylessforstorage.co.uk",
              "http://www.newcastle-self-storage.com", "http://storagecentres.co.uk", "http://www.storagestockport.com",
              "http://www.easyaccessselfstorage.co.uk", "http://www.cheshire-storage.co.uk",
              "http://www.storage-stockport.com", "http://www.a1securestorage.co.uk",
              "http://www.gblinersselfstore.co.uk", "http://www.bigboxstorage.com", "http://www.easethesqueeze.co.uk",
              "http://www.beestored.com", "http://www.brighton-removals.co.uk", "http://easistore.co.uk",
              "https://www.selfstoragespace.co.uk", "http://www.eliteselfstorage.co.uk",
              "http://eckersleysremovals.co.uk", "http://www.outerspacestorage.co.uk",
              "http://dunscarselfstorage.co.uk", "http://www.orangeboxselfstorage.com", "http://www.qcspace.co.uk",
              "http://www.herringtonstorage.co.uk", "http://www.lowfellremovals.co.uk",
              "http://www.storagemedway.co.uk", "http://www.wildselfstorage.co.uk",
              "http://www.selfstorageinmedway.co.uk", "http://allsecureselfstorage.com",
              "http://www.thamesselfstorage.co.uk", "http://chesleystorage.co.uk", "http://www.mightysafestorage.co.uk",
              "http://www.acmeselfstore.co.uk", "http://www.sjonescontainers.co.uk", "http://storagegreenwich.org.uk",
              "http://southgloucesterselfstorage.co.uk", "http://www.thornburyselfstorage.co.uk",
              "http://www.southglos.gov.uk", "http://www.terryluntremovals.co.uk",
              "http://www.terryluntremovalsandstorage.co.uk", "http://www.storageforlondon.com",
              "http://urbanlocker.co.uk", "http://www.makespaceselfstorage.co.uk", "http://www.astoragesolution.co.uk",
              "https://www.plymouthselfstorage.co.uk", "http://spacestorage.co.uk", "http://quickstore.co.uk",
              "http://www.plymouthremovers.co.uk", "http://www.selfstoragemiltonkeynes.co.uk",
              "http://www.selfstorageinmiltonkeynes.co.uk", "http://www.abselfstorage.co.uk",
              "http://www.ab-selfstorage.co.uk", "http://www.rotherhamselfstorage.co.uk",
              "http://www.canklowstorage.co.uk", "http://removals-in-rotherham.co.uk",
              "http://www.junction1storage.co.uk", "http://hullselfstorage.com", "http://easyselfstore.co.uk",
              "http://www.tnh-storage.co.uk", "http://titancontainers.com", "http://removalshull.com",
              "http://www.poppystorage.co.uk", "http://www.wolves-selfstorage.co.uk",
              "http://www.chillingtonselfstorage.co.uk", "http://m54selfstorage.co.uk", "http://burkebros.co.uk",
              "http://www.wolverhamptonremovalsandstorage.co.uk", "http://www.em-storage.co.uk",
              "http://www.derbyselfstore.co.uk", "http://www.jumbostorage.co.uk", "http://www.super-storage.co.uk",
              "http://www.bigfootstorage.com", "http://www.store-safe.co.uk", "http://www.jumboselfstorage.co.uk",
              "http://www.the-box-room.com", "http://www.selfstoragesouthamptonuk.co.uk",
              "http://www.sentryselfstorage.co.uk", "http://www.cbainremovals.co.uk",
              "http://www.apexselfaccessstorage.co.uk", "http://www.grgstorage.co.uk", "http://www.flexistore.co.uk",
              "http://www.guardianstorage.com", "https://www.ezstorage.com", "https://www.storageetc.com",
              "http://www.miniustoragewestminster.com", "http://www.citystore.ltd.uk", "http://www.aaselfstorage.com",
              "http://stashselfstorage.com", "http://www.selfstoresolutions.co.uk", "http://www.taylorsremovals.org",
              "http://www.chambersselfstorage.co.uk", "http://www.storageoldham.co.uk",
              "http://www.oldhamselfstorage.co.uk", "http://www.meadowselfstorage.co.uk",
              "http://www.greenacresselfstorage.co.uk", "http://www.highburyselfstorage.co.uk",
              "http://www.metro-storage.co.uk", "http://www.selfstoreit.co.uk", "http://www.sywellaerodrome.co.uk",
              "http://www.removalsnorthampton.co.uk", "http://www.alertselfstorage.co.uk",
              "http://www.ashtonselfstore.com", "http://www.storageplace.co.uk", "http://www.whiteselfstorage.co.uk",
              "http://www.rivermillselfstore.co.uk", "http://tamesidestorage.co.uk", "http://www.m4selfstore.co.uk",
              "http://www.anchorselfstorage.co.uk", "http://www.rochdaleselfstorage.co.uk",
              "http://www.simplestorage.co", "http://www.selfstorageunitsrochdale.co.uk",
              "http://www.lockbox-selfstorage.co.uk", "http://www.ardenselfstorage.co.uk",
              "http://www.titanstorage.co.uk", "http://moversandstorers.co.uk", "http://www.orangeselfstorage.co.uk",
              "http://coombefarmselfstorage.co.uk", "http://www.yeates.co.uk", "http://www.containerteam.co.uk",
              "http://www.portmarine-selfstorage.co.uk", "http://www.caravanstoragesouthwest.co.uk",
              "http://www.burringtoncombeselfstorage.co.uk", "http://www.greencreststorage.org.uk",
              "http://www.calderdaleselfstorage.com", "http://www.keepsafeselfstorage.co.uk",
              "http://warringtonselfstorage.co.uk", "http://warringtonstoragecontainers.com",
              "http://www.innerspacestations.com", "http://www.greenspaceselfstorage.co.uk",
              "http://www.hughesremovals.co.uk", "http://www.mitchellstorage.co.uk", "http://www.aclassstorage.co.uk",
              "http://www.gallaghersremovals.co.uk", "http://www.harkersremovers.co.uk",
              "http://www.gsrselfstorage.co.uk", "http://a1-selfstorage.co", "http://www.quickstoragegateshead.co.uk",
              "http://www.gatesheadstorage.co.uk", "http://www.securestore365.com",
              "http://www.kingstoragemansfield.co.uk", "http://www.cookesstorage.co.uk",
              "http://www.dickensselfstorage.co.uk", "http://storeit4u.co.uk", "http://www.reds-removals.co.uk",
              "http://storagerichmonduponthames.co.uk", "https://www.storeandsecure.co.uk",
              "http://www.storagebournemouth.co.uk", "http://www.avonselfstorage.co.uk",
              "http://www.andyselfstorage.co.uk", "http://www.1staccessselfstorage.co.uk",
              "http://www.morespacestorage.co.uk", "http://www.readsremovals.com",
              "http://www.surestore-self-storage.co.uk", "http://aylesburyselfstorage.co.uk",
              "http://www.storengo.co.uk", "http://www.herefordstorage.co.uk", "http://woodlandsselfstore.co.uk",
              "http://pughsselfstorage.co.uk", "http://www.wallisselfstorage.co.uk", "http://www.aubreystorage.co.uk",
              "http://www.smallbrookselfstorage.co.uk", "http://www.driveinselfstore.co.uk",
              "http://www.peldon-storage.co.uk", "http://www.littlegreenselfstorage.com",
              "http://www.easy-store247.co.uk", "http://www.schofieldremovals.co.uk",
              "http://www.reliable-removals.co.uk", "http://dragonselfstorage.co.uk",
              "http://www.newforestselfstorage.co.uk", "http://www.lymingtonselfstorage.co.uk",
              "http://www.eazystore.co.uk", "http://www.amplestorage.co.uk", "http://thestorageteam.co.uk",
              "http://www.fortknoxstorageltd.co.uk", "http://charnwoodselfstorage.co.uk",
              "http://www.charnwood-removals.co.uk", "http://www.charnwoodbusiness.com",
              "http://www.storagebelconnen.com.au", "http://www.squirrelselfstorage.co.uk",
              "http://barretts-selfstorage.co.uk", "http://www.bensstoragesolutions.co.uk",
              "http://www.vikingselfstorage.co.uk", "http://alexanders-removals.co.uk",
              "http://bluntishamselfstore.co.uk", "http://www.hunts-storage.uk", "http://www.simplystoreit.co.uk",
              "http://www.chappellsremovals.co.uk", "http://www.ownremovals.co.uk", "http://www.frarystorage.co.uk",
              "http://honeycombstorage.co.uk", "http://www.chelmsfordmoving.co.uk", "http://www.tjstorage.co.uk",
              "http://www.wrekinremovals.co.uk", "http://www.wrekinselfstore.co.uk", "http://www.goodwins-removals.com",
              "http://www.containerking.co.uk", "http://borrillcaravanstorage.co.uk", "http://www.scott-storage.co.uk",
              "http://www.caravanownersclub.co.uk", "http://www.bedfordselfstorage.co.uk",
              "http://storage-bedfordshire.co.uk", "http://www.bigbluesquirrel.co.uk",
              "http://www.1bigstoragesolutions.co.uk", "http://www.securestorageessex.co.uk",
              "http://www.flexible-storage.co.uk", "http://www.somersetstorage.co.uk",
              "http://www.loadnlockstorage.co.uk", "http://beehiveselfstorage.co.uk", "http://www.sparkfordstorage.com",
              "http://www.selfstoragesomerset.co.uk", "http://www.aylesfordselfstorage.co.uk",
              "http://www.storageplanet.co.uk", "http://www.readingstoragesolutions.co.uk",
              "http://www.easystorage.co.uk", "http://www.wokinghamstorage.co.uk", "http://www.eversleystorage.co.uk",
              "http://www.ustoresandhurst.co.uk", "http://www.selfstoragewokingham.co.uk",
              "http://aandsselfstorage.co.uk", "http://www.needaspace.co.uk", "http://www.selfstoragecentre.com",
              "http://www.dukesstorage.co.uk", "http://www.caravan-creche.co.uk", "http://www.chelseaselfstorage.co.uk",
              "http://www.harrogateselfstorage.co.uk", "http://www.rocketstorageharrogate.co.uk",
              "http://www.fishers-harrogate.co.uk", "http://www.spacecentrestorage.co.uk",
              "http://www.towncentrestorage.co.uk", "https://newburyselfstore.co.uk",
              "http://www.newburycontainerstorageltd.co.uk", "http://arunselfstorage.co.uk",
              "http://www.cambourneselfstorage.co.uk", "http://www.blueboxstorage.com",
              "http://www.kingslynnselfstorage.co.uk", "http://www.kingslynnstorage.co.uk",
              "http://www.4securestorage.co.uk", "https://www.west-norfolk.gov.uk", "http://eastcoaststorage.co.uk",
              "http://www.smithsremovals.com", "http://www.ustoresolutions.co.uk",
              "http://www.britannia-self-store.com", "http://www.barnfieldcaravans.co.uk",
              "http://www.selfstoreuk.co.uk", "http://www.wrwarburton-storage.co.uk", "http://www.westoeremovals.com",
              "http://movingandstorage.co.uk", "http://www.nestings-storage.co.uk", "http://fleetremovals.co.uk",
              "http://www.gostorego.co.uk", "http://www.safe-self-storage.com", "http://www.stalbansministorage.com",
              "http://storagelanduk.co.uk", "http://www.grosvenorremovals.co.uk", "http://midsussexremovals.uk",
              "http://www.mpdremovals.com", "http://www.fort-locks-self-storage.co.uk",
              "http://www.cherwellvalleysilos.co.uk", "http://www.cherwell.gov.uk", "https://www.cherwell.com",
              "http://www.herts-storage.co.uk", "http://betterremovals.co.uk", "http://www.atlasoflondon.co.uk",
              "http://www.removalandstorage.com", "http://www.johnsonsmovingservices.co.uk",
              "http://www.funnellsremovals.com", "http://www.accesstransport.co.uk", "http://reliable-removals.com",
              "http://www.247removalsandstorage.com", "http://www.theselfstoragewarehouse.com",
              "http://storage-units-preston.co.uk", "http://www.storagepreston.com"]
new_list_of_sites = []
new_list = []

sort_of_link = re.compile(r'(https?://w{,3}\.?([^/"]*))')
for item in list_sites:
    iterator = sort_of_link.finditer(item)

    for match in iterator:
        if str(match.group(2)) not in new_list:
            new_list.append(match.group(2))
            new_list_of_sites.append(str(match.group(1)))

print(new_list)
print(new_list_of_sites)